language: r
cache: packages

r_packages:
  - devtools
  - ggplot2
  - hunspell
  - xml2

r_github_packages:
  - jimhester/covr
  - jimhester/lintr
  - richelbilderbeek/babette
  - richelbilderbeek/beastier
  - richelbilderbeek/beautier
  - richelbilderbeek/mauricer
  - richelbilderbeek/tracerer
  - MangoTheCat/goodpractice
  - KlausVigo/phangorn
  - ropensci/spelling

before_script:
  - # Java 8
  - sudo apt-get install -qq oracle-java8-installer
  - sudo apt-get install oracle-java8-set-default
  - Rscript -e "beastier::install_beast2()"

script:
  - Rscript scripts/test_brute_force_1.R
  #- travis_wait 30 Rscript scripts/test_brute_force_2_unlinked.R
