language: r
# dist: bionic # Uncomment until fix of https://travis-ci.community/t/r-install-broken-travis-ci-rstudio-org-returns-403/9640
cache: packages

# Use bleeding-edge version of babette
r_github_packages:
  - ropensci/tracerer
  - ropensci/babette

before_install:
  # Fix rJava error, from https://travis-ci.community/t/cannot-connect-to-java-from-r/9754/8
  - sudo $(which R) CMD javareconf

before_script:
  - # if Linux, show distro
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cat /proc/version; fi
  - # Java
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then R CMD javareconf; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then R --quiet -e 'install.packages("rJava", type="source", repos="http://cran.us.r-project.org")'; fi
  - # BEAST2
  - Rscript -e "beastier::install_beast2()"

after_failure:
  # Download thesis
  - Rscript -e 'download.file("https://www.rug.nl/research/portal/files/132028374/Complete_thesis.pdf", tempfile())'

after_success:
  # Download thesis
  - Rscript -e 'download.file("https://www.rug.nl/research/portal/files/132028374/Complete_thesis.pdf", tempfile())'


