language: r
cache: packages

r_packages:
  - devtools
  - ggplot2
  - hunspell
  - xml2

r_github_packages:
  - jimhester/covr
  - jimhester/lintr
  - KlausVigo/phangorn
  - ropensci/beastier
  - ropensci/mauricer
  - ropensci/babette
  - MangoTheCat/goodpractice
  - ropensci/spelling

before_script:
  - # Java 8
  - sudo apt-get install -qq oracle-java8-installer
  - sudo apt-get install oracle-java8-set-default
  - Rscript -e "beastier::install_beast2()"
